CREATE DATABASE CarDealership;
GO

USE CarDealership;
GO

CREATE TABLE Client (
    Id INT PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL
);

CREATE TABLE Store (
    Id INT PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL,
    Address NVARCHAR(255) NOT NULL,
    City NVARCHAR(50) NOT NULL
);

CREATE TABLE Car (
    Id INT PRIMARY KEY,
    Manufacturer NVARCHAR(50) NOT NULL,
    Model NVARCHAR(50) NOT NULL,
    Price MONEY NOT NULL
);

CREATE TABLE [Order] (
    Id INT PRIMARY KEY,
    ClientId INT NOT NULL FOREIGN KEY REFERENCES Client(Id),
    StoreId INT NOT NULL FOREIGN KEY REFERENCES Store(Id),
    CarId INT NOT NULL FOREIGN KEY REFERENCES Car(Id),
    PurchasePrice MONEY NOT NULL
);
